import FieldData from "../../Common/Actions/FieldData";
import { ScreenType } from "./Constants";
let iState = {};
iState = {
  WindowHeight: window.innerHeight,
  WindowWidth: window.innerWidth,
  GridData: [],
  ResultCount: 0,
  ShowProgressPanel: false,
  IsReadOnlyMode: false,
  GridDataLoadingId: Date.now(), //Just a flag to intiate grid data reload from different comoonents
  Toast: {
    Id: Date.now(),
    Message: null,
  },
  CallId: "",
  CallTrackerTime: "",
  IsAutoCallStop: false,
  ActionState: {
    CurrentAction: "",
    ActionTriggerId: "",
  },
  CurrentScreen: ScreenType.Grid,
  MasterData: {
    CapDetails: [],
    Clients: [],
    Statuses: [],
    RequestTypes: [],
    RequestMode: ["Phone", "Portal", "Email", "Voicemail"],
    ChannelTypes:  [
      {
        Code: "PHONE",
        Name: "Phone",
      },
      {
        Code: "PORTAL",
        Name: "Portal",
      },
      {
        Code: "EMAIL",
        Name: "Email",
      },
      {
        Code: "VOICEMAIL",
        Name: "VoiceMail",
      },
    ],
  },
  SearchParameters: {
    FromDate: new FieldData(),
    ToDate: new FieldData(),
    StatusIds: [],
    Channels: [],
    SearchPanelHasError: false,
    MaxNoOfDaysToSearch: 90,
    Client: new FieldData(),
    AuditIds: new FieldData(),
    ClientName: "",
  },
  SelectedRequestOriginalData: null,
  CallerInformation: {
    CallerName: new FieldData(""),
    CallerNumber: new FieldData(""),
    OutreachContact: new FieldData(""),
    RequesterMail: new FieldData(""),
    VerifiedUsing: new FieldData(""),
  },
  RequestForm: {
    CallNotStartedApprove: false,
    IsAddRequest: false,
    HasChanges: false,
    RequestId: "",
    AddAnother: false,
    RequestTypeId: new FieldData(),
    CallerName: new FieldData(),
    CallerNumber: new FieldData(),
    OutreachContact: new FieldData(),
    RequesterMail: new FieldData(),
    CapId: new FieldData(),
    ClientId: "",
    AuditProgramId: "",
    AuditId: new FieldData(),
    AdditionalAuditIds: new FieldData(),
    FlowName: "",
    FlowId: "",
    ProviderName: "",
    PatientName: "",
    ProviderAddress: "",
    StatusId: "",
    StatusCode: "",
    ChannelCode: "",
    StartedAt: new Date(),
    IsAddAnother: false,
    IsReadOnly: false,
    IsCallerNumberRequired: false,
    IsEmailRequired: false,
    IsVerifiedUsingRequired: false,
    IsResponseRequired: false,
    RequestTypeCode: '',
    ActiveQuery: {
      ShowEditCard: false,
      HasChanges: false,
      IsFollowUp: false,
      Id: "",
      AttendedAt: new Date(),
      AttendedBy: "",
      Query: new FieldData(""),
      Response: new FieldData(""),
      UpdatedBy: "",
      UpdatedOn: new Date(),
      RequestMode: new FieldData("Phone"),
      VerifiedUsing: new FieldData(""),
      DisableQueryWindow: false,
    },

    QueryDetails: [
      {
        Id: "",
        AttendedAt: new Date(),
        AttendedBy: "",
        Query: "",
        Response: "",
        UpdatedBy: "",
        UpdatedOn: new Date(),
        VerifiedUsing: "",
        RequestMode: "",
        NotificationStatus: "",
        NotifiedAt: new Date(),
        RequestDataJson: {},
      },
    ],
    CallHistory: null,
  },
  ShowCurrentCallRequests: false,
  CurrentCallRequests: [],
  IsExportDisabled: true,
  ConfirmationDialog: {
    action: "",
    message: "",
    visible: false,
    submitText: "",
    cancelText: "",
    actionParameter: null,
  },
  PreviousQueryDetails: {
    Query: "",
    Response: "",
  },
};
export const initialState = iState;
